Repository bcgov/smk-mrdt, pull requests merged in 2022-08, with the labels that each got.

#22 Use Esri vector basemaps
  package-lock.json
  package.json
  smk-config.json
Labels: 20220721-1603

#25 Whitepace
  index.html
Labels: 20220815-2258

#26 Fix attribute display
  layers/-smk-catalog.json
  smk-config.json
Labels: 20220816-2150

#33 Add missing attributes
  smk-config.json
Labels: 20220818-2043
